server:
  port: 8100
spring:
  application:
    name: book-service
  datasource:  
     driver-class-name: org.postgresql.Driver
     url: jdbc:postgresql://localhost:5432/book_service
     username: postgres
     password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: NON_NULL 
    serialization:
      fail-on-empty-beans: false
  flyway:
    url: jdbc:postgresql://localhost:5432/
    shemas: book_service
    user: postgres
    password: 123456
  client:
    cambio-service:
      url: http://localhost:8101
